<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FUpdateEventTimeStampedWithSystemTimeStamepd" Id="{8b4290ba-adfe-4acd-a2ff-69de9fbf2884}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FUpdateEventTimeStampedWithSystemTimeStamepd 
VAR_INPUT
	st_event : REFERENCE TO ST_Events ;
END_VAR
VAR
	fbGetSystemTime : GETSYSTEMTIME;
	
	st_filetime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGetSystemTime( timeLoDw => st_filetime.dwLowDateTime,
				 timeHiDW => st_filetime.dwHighDateTime);
				 
st_event.dtTimeStamped := FILETIME_TO_DT(st_filetime);]]></ST>
    </Implementation>
    <LineIds Name="FUpdateEventTimeStampedWithSystemTimeStamepd">
      <LineId Id="7" Count="0" />
      <LineId Id="12" Count="1" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>